import type { Metadata } from 'next'
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from './PrivComponents/Navbar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className='h-full' >
      <body className={`${geistSans.variable} ${geistMono.variable} h-full `}>
        <ClerkProvider>
          <div className="fixed top-4 right-4 z-50 ">
        <UserButton appearance={{UserButton:{width:"50px",height:"100px"}}}/>
      </div>
          {children}
          <Navbar/>
        </ClerkProvider>
      </body>
    </html>
  )
}